# Generated by Django 5.0.14 on 2025-08-25 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0002_initial'),
        ('vendor', '0002_remove_vendorprice_price_cents_vendorprice_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='scrape',
            options={'ordering': ['-scrape_time'], 'verbose_name': 'Scrape', 'verbose_name_plural': 'Scrapes'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-expires_at'], 'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(blank=True, help_text='The upload session that created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace',
            field=models.ForeignKey(help_text='The marketplace where this product is sold', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.marketplace'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace_child_sku',
            field=models.CharField(help_text='Marketplace-specific child SKU', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketplace_parent_sku',
            field=models.CharField(blank=True, help_text='Marketplace-specific parent SKU', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(help_text='The specific store within the marketplace', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variation_id',
            field=models.CharField(blank=True, help_text='Product variation identifier if applicable', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor who supplies this product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_sku',
            field=models.CharField(help_text="Vendor's SKU/item number (used for eBay item number)", max_length=255),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='error_code',
            field=models.CharField(blank=True, help_text='Error code if scraping failed', max_length=50),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Scraped price in cents (deprecated - use VendorPrice.price)', null=True),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='product',
            field=models.ForeignKey(help_text='The product that was scraped', on_delete=django.db.models.deletion.CASCADE, related_name='scrapes', to='products.product'),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Complete raw response from scraping operation'),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='scrape_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this scraping operation occurred'),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='stock',
            field=models.IntegerField(blank=True, help_text='Scraped stock quantity', null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this upload record expires'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes about this upload'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='original_name',
            field=models.CharField(help_text='Original filename as uploaded by user', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stored_key',
            field=models.CharField(help_text='Path where the file is stored on disk', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'vendor_sku', 'marketplace', 'store', 'variation_id')},
        ),
        migrations.AddIndex(
            model_name='scrape',
            index=models.Index(fields=['product', '-scrape_time'], name='products_sc_product_231788_idx'),
        ),
    ]
