# Generated by Django 5.0.14 on 2025-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_scrape_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace_external_id',
            field=models.CharField(blank=True, help_text='External ID provided by the marketplace (eBay ID, Amazon ASIN, etc.)', max_length=255),
        ),
    ]
