# Generated by Django 5.0.14 on 2025-08-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_marketplace_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketplace_external_id',
            field=models.CharField(blank=True, help_text='External ID provided by the marketplace (eBay ID, Amazon ASIN, etc.)', max_length=255, null=True),
        ),
    ]
