# Generated by Django 5.0.14 on 2025-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_marketplace_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='calculated_shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated shipping price after business rules', max_digits=10),
        ),
        migrations.AddField(
            model_name='scrape',
            name='error_details',
            field=models.TextField(blank=True, help_text='Detailed error information for debugging'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='final_inventory',
            field=models.IntegerField(blank=True, help_text='Final inventory after business rules', null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after business rules (price + shipping)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scrape',
            name='needs_rescrape',
            field=models.BooleanField(default=False, help_text='Whether this product needs to be rescraped'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_ended_listings',
            field=models.TextField(blank=True, help_text='Raw ended listings info from scraping'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_handling_time',
            field=models.TextField(blank=True, help_text='Raw handling time info from scraping'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_price',
            field=models.CharField(blank=True, help_text='Raw price text from scraping', max_length=100),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_quantity',
            field=models.TextField(blank=True, help_text='Raw quantity info from scraping'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_seller_away',
            field=models.TextField(blank=True, help_text='Raw seller away info from scraping'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='raw_shipping',
            field=models.CharField(blank=True, help_text='Raw shipping info from scraping', max_length=200),
        ),
        migrations.AddIndex(
            model_name='scrape',
            index=models.Index(fields=['needs_rescrape'], name='products_sc_needs_r_7b4e85_idx'),
        ),
    ]
