# Generated by Django 5.2.3 on 2025-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0006_add_ebayau_scrape_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='processed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='progress_data',
            field=models.JSONField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='upload',
            name='stored_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('marketplace', 'store', 'marketplace_child_sku')},
        ),
        migrations.AlterModelTable(
            name='upload',
            table='products_upload',
        ),
    ]
