# Generated by Django 5.2.3 on 2025-08-16 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_value', models.CharField(default='MAX', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('from_value', 'to_value')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key_enc', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('scraping_enabled', models.BooleanField(default=True)),
                ('scraping_interval_hours', models.IntegerField(default=24)),
                ('last_scrape_time', models.DateTimeField(blank=True, null=True)),
                ('price_update_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='marketplace.marketplace')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='marketplace.store')),
            ],
        ),
        migrations.CreateModel(
            name='StorePriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marketplace_fees_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_settings', to='marketplace.store')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRangeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.pricerange')),
                ('inventory_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ranges', to='marketplace.storeinventorysettings')),
            ],
            options={
                'unique_together': {('inventory_settings', 'price_range')},
            },
        ),
        migrations.CreateModel(
            name='PriceRangeMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('minimum_margin_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.pricerange')),
                ('price_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_ranges', to='marketplace.storepricesettings')),
            ],
            options={
                'unique_together': {('price_settings', 'price_range')},
            },
        ),
    ]
